# Generated by Django 4.2.6 on 2023-11-06 13:28

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('umur', models.IntegerField()),
                ('golongan', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pengolahan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampel_1', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_2', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_3', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_4', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_5', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_6', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_7', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_8', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_9', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_10', models.ImageField(upload_to=core.models.generate_filename)),
                ('sampel_11', models.ImageField(upload_to=core.models.generate_filename)),
                ('profil', models.ImageField(upload_to='profil/')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengolahan', to='core.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_absensi', models.DateTimeField()),
                ('status_absensi', models.CharField(max_length=255)),
                ('sisa_absensi', models.IntegerField()),
                ('berapa_kali_absensi', models.IntegerField()),
                ('pengolahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengolahan')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='core.customuser')),
            ],
        ),
    ]
