# Generated by Django 4.2.6 on 2023-11-06 14:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengolahan',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_10',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_11',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_6',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_7',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_8',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_9',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename),
        ),
    ]
