# Generated by Django 4.2.6 on 2023-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_10',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_11',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_3',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_4',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_5',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_6',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_7',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_8',
        ),
        migrations.RemoveField(
            model_name='pengolahan',
            name='sampel_9',
        ),
    ]
