# Generated by Django 4.2.6 on 2023-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_absensi_berapa_kali_absensi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='berapa_kali_absensi',
            field=models.IntegerField(default=2),
        ),
    ]
