# Generated by Django 4.2.6 on 2023-11-07 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_absensi_berapa_kali_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengolahan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengolahan', to=settings.AUTH_USER_MODEL),
        ),
    ]
