# Generated by Django 4.2.6 on 2023-11-11 10:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pengolahan_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengolahan',
            name='sampel_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.generate_filename2),
        ),
    ]
