# Generated by Django 4.2.6 on 2023-11-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_absensi_status_absensi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='sisa_absensi',
        ),
    ]
