# Generated by Django 4.2.6 on 2023-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_absensi_sisa_absensi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengolahan',
            name='profil',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tanggal_absensi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
