# Generated by Django 4.2.6 on 2023-11-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_absensi_sisa_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
    ]
